XML_FOLDER = 'Annotations'
GENERATED_DATA = 'GeneratedData'
TRAIN_FOLDER = 'Train'
VAL_FOLDER = 'Val'
TEST_FOLDER = 'Test'
LABEL = 'Label'


CARD_HEIGHT = 144
CARD_WIDTH = 224

BACKGROUND_TOTAL_FILES = 10   

MIN_CARDS = 1
MAX_CARDS = 1  

BORDER_WHITE_AREA = 0 

IMAGE_SIZE = 224 

TOTAL_TRAIN_IMAGES = 120 
TOTAL_VALIDATION_IMAGES = 10 