XML_FOLDER = 'Annotations'
GENERATED_DATA = 'GeneratedData'
TRAIN_FOLDER = 'Train'
VAL_FOLDER = 'Val'
TEST_FOLDER = 'Test'
LABEL = 'Label'


CARD_HEIGHT = 180
CARD_WIDTH = 280

BACKGROUND_TOTAL_FILES = 16   

MIN_CARDS = 1
MAX_CARDS = 1  

BORDER_WHITE_AREA = 0 

IMAGE_SIZE = 400 

TOTAL_TRAIN_IMAGES = 50 
TOTAL_VALIDATION_IMAGES = 10 